name       : pyatspi2
version    : 2.26.0
release    : 2
source     :
    - https://github.com/GNOME/pyatspi2/archive/PYATSPI_2_26_0.tar.gz : 2ca174a03c0fe2792f50ec068702e9ca4e3026e69ce4640050ed669082204b1d
license    :
    - GPL-2.0
    - LGPL-2.0
component  : programming.python
summary    : A python client library for the AT-SPI D-Bus accessibility infrastructure.
description: |
    A python client library for the AT-SPI D-Bus accessibility infrastructure.
builddeps  :
    - pkgconfig(dbus-glib-1)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(pygobject-3.0)
    - python3-dbus
rundeps    :
    - python3-dbus
    - python-gobject
setup      : |
    %autogen --disable-static --enable-tests --with-python=/usr/bin/python3
build      : |
    %make
install    : |
    %make_install
