name       : pyatspi2
version    : 2.20.2
release    : 1
source     :
    - https://github.com/GNOME/pyatspi2/archive/PYATSPI_2_20_2.tar.gz : 6f2e3392505297fe6fb6610ed83281f006c761f46ed6b09cc9eecbd880bb4568
license    : GPL-2.0
component  : programming.python
summary    : A python client library for the AT-SPI D-Bus accessibility infrastructure.
description: |
    A python client library for the AT-SPI D-Bus accessibility infrastructure.
builddeps  :
    - pkgconfig(dbus-glib-1)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(pygobject-3.0)
    - python3-dbus
rundeps    :
    - python3-dbus
    - python-gobject
setup      : |
    %autogen --disable-static --enable-tests --with-python=/usr/bin/python3
build      : |
    %make
install    : |
    %make_install
