name       : pyatspi2
version    : 2.45.1
release    : 11
source     :
    - https://download.gnome.org/sources/pyatspi/2.45/pyatspi-2.45.1.tar.xz : bba7c2663430e55123a443f37a5a29e7beb8b01649bdb2969ad3eb941daac1ae
license    :
    - GPL-2.0-or-later
    - LGPL-2.0-or-later
component  : programming.python
summary    : A python client library for the AT-SPI D-Bus accessibility infrastructure.
description: |
    A python client library for the AT-SPI D-Bus accessibility infrastructure.
builddeps  :
    - pkgconfig(dbus-glib-1)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(pygobject-3.0)
    - python3-dbus
rundeps    :
    - python3-dbus
    - python-gobject
setup      : |
    %reconfigure --disable-static --enable-tests --with-python=/usr/bin/python3
build      : |
    %make
install    : |
    %make_install
